services:
  - type: web
    name: satellite-crop-health
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: RESET_DB
        value: false
